ALTER TABLE "SystemControl" ADD COLUMN "transportUsdPerCbm" REAL NOT NULL DEFAULT 85.714653;
ALTER TABLE "SystemControl" ADD COLUMN "customsRakovinaUsd" REAL NOT NULL DEFAULT 6.65;
ALTER TABLE "SystemControl" ADD COLUMN "customsUnitazUsd" REAL NOT NULL DEFAULT 18.81;
ALTER TABLE "SystemControl" ADD COLUMN "customsSifonUsd" REAL NOT NULL DEFAULT 0.82;
ALTER TABLE "SystemControl" ADD COLUMN "customsSmesitelUsd" REAL NOT NULL DEFAULT 1.47;
ALTER TABLE "SystemControl" ADD COLUMN "customsOynaUsd" REAL NOT NULL DEFAULT 0;
